// Package profile implements client-spoofing profiles: the per-torrent-client
// recipe for building an announce request (peer id, key, query string,
// headers) that makes ratioreign's fake seeding indistinguishable, at the
// protocol level, from the real client it impersonates.
//
// The JSON schema intentionally matches Joal's `.client` files (see
// https://github.com/anthonyraymond/joal, resources/clients/*.client) so the
// large existing library of community-maintained profiles can be dropped
// into ratioreign's profiles/ directory unmodified.
package profile

import (
	"crypto/rand"
	"encoding/json"
	"fmt"
	"math/big"
	"net/url"
	"os"
	"regexp"
	"runtime"
	"strings"
)

type Algorithm struct {
	Type    string `json:"type"`
	Length  int    `json:"length,omitempty"`
	Pattern string `json:"pattern,omitempty"`
	Min     int64  `json:"min,omitempty"`
	Max     int64  `json:"max,omitempty"`
}

type KeyGenerator struct {
	Algorithm Algorithm `json:"algorithm"`
	RefreshOn string    `json:"refreshOn"`
	KeyCase   string    `json:"keyCase"`
}

type PeerIDGenerator struct {
	Algorithm       Algorithm `json:"algorithm"`
	RefreshOn       string    `json:"refreshOn"`
	ShouldURLEncode bool      `json:"shouldUrlEncode"`
}

type URLEncoder struct {
	EncodingExclusionPattern string `json:"encodingExclusionPattern"`
	EncodedHexCase           string `json:"encodedHexCase"`
}

type Header struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// Profile is a single client-spoofing recipe, loaded from a *.client JSON
// file.
type Profile struct {
	Name            string          `json:"-"`
	KeyGenerator    *KeyGenerator   `json:"keyGenerator,omitempty"`
	PeerIDGenerator PeerIDGenerator `json:"peerIdGenerator"`
	URLEncoder      URLEncoder      `json:"urlEncoder"`
	Query           string          `json:"query"`
	Numwant         int             `json:"numwant"`
	NumwantOnStop   int             `json:"numwantOnStop"`
	RequestHeaders  []Header        `json:"requestHeaders"`
	exclusionRe     *regexp.Regexp  `json:"-"`
}

// Load reads a single *.client profile file.
func Load(path string) (*Profile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var p Profile
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("profile: %s: %w", path, err)
	}
	p.Name = strings.TrimSuffix(strings.TrimSuffix(path, ".client"), ".json")
	if idx := strings.LastIndexByte(p.Name, '/'); idx >= 0 {
		p.Name = p.Name[idx+1:]
	}
	if p.URLEncoder.EncodingExclusionPattern != "" {
		re, err := regexp.Compile(p.URLEncoder.EncodingExclusionPattern)
		if err != nil {
			return nil, fmt.Errorf("profile: %s: invalid encodingExclusionPattern: %w", path, err)
		}
		p.exclusionRe = re
	}
	return &p, nil
}

// Session holds the per-torrent identity (peer id, key) generated by a
// profile for one seeding session. A fresh Session is created whenever a
// torrent is (re)started; refreshOn == "ALWAYS" additionally regenerates the
// relevant field before every announce (see Refresh).
type Session struct {
	profile *Profile
	peerID  string
	key     string
}

// NewSession generates the peer id (and key, if the profile uses one) for a
// newly (re)started torrent.
func (p *Profile) NewSession() (*Session, error) {
	s := &Session{profile: p}
	peerID, err := p.generatePeerID()
	if err != nil {
		return nil, fmt.Errorf("profile: peer id: %w", err)
	}
	s.peerID = peerID
	if p.KeyGenerator != nil {
		key, err := p.generateKey()
		if err != nil {
			return nil, fmt.Errorf("profile: key: %w", err)
		}
		s.key = key
	}
	return s, nil
}

// Refresh regenerates identity fields whose refreshOn policy is "ALWAYS".
// Every other policy (NEVER, TIMED, TORRENT_PERSISTENT, ...) collapses to
// "generate once per session" in ratioreign's simpler long-running-process
// model, so no further action is needed for those.
func (s *Session) Refresh() error {
	if s.profile.PeerIDGenerator.RefreshOn == "ALWAYS" {
		peerID, err := s.profile.generatePeerID()
		if err != nil {
			return fmt.Errorf("profile: peer id: %w", err)
		}
		s.peerID = peerID
	}
	if s.profile.KeyGenerator != nil && s.profile.KeyGenerator.RefreshOn == "ALWAYS" {
		key, err := s.profile.generateKey()
		if err != nil {
			return fmt.Errorf("profile: key: %w", err)
		}
		s.key = key
	}
	return nil
}

func (p *Profile) generatePeerID() (string, error) {
	switch p.PeerIDGenerator.Algorithm.Type {
	case "REGEX":
		return randomFromPattern(p.PeerIDGenerator.Algorithm.Pattern)
	case "RANDOM_POOL_WITH_CHECKSUM":
		return randomPoolWithChecksum(20)
	default:
		return "", fmt.Errorf("unsupported peerIdGenerator algorithm %q", p.PeerIDGenerator.Algorithm.Type)
	}
}

func (p *Profile) generateKey() (string, error) {
	kg := p.KeyGenerator
	var key string
	var err error
	switch kg.Algorithm.Type {
	case "HASH":
		key, err = randomHex(kg.Algorithm.Length, false)
	case "HASH_NO_LEADING_ZERO":
		key, err = randomHex(kg.Algorithm.Length, true)
	case "REGEX":
		key, err = randomFromPattern(kg.Algorithm.Pattern)
	case "DIGIT_RANGE_TRANSFORMED_TO_HEX_WITHOUT_LEADING_ZEROES":
		key, err = randomHexFromRange(kg.Algorithm.Min, kg.Algorithm.Max)
	default:
		return "", fmt.Errorf("unsupported keyGenerator algorithm %q", kg.Algorithm.Type)
	}
	if err != nil {
		return "", err
	}
	switch kg.KeyCase {
	case "upper":
		key = strings.ToUpper(key)
	case "lower":
		key = strings.ToLower(key)
	}
	return key, nil
}

func randomHex(length int, noLeadingZero bool) (string, error) {
	const digits = "0123456789abcdef"
	const digitsNZ = "123456789abcdef"
	var b strings.Builder
	for i := 0; i < length; i++ {
		alphabet := digits
		if i == 0 && noLeadingZero {
			alphabet = digitsNZ
		}
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(alphabet))))
		if err != nil {
			return "", err
		}
		b.WriteByte(alphabet[n.Int64()])
	}
	return b.String(), nil
}

func randomHexFromRange(min, max int64) (string, error) {
	if max <= min {
		return "", fmt.Errorf("invalid digit range [%d,%d)", min, max)
	}
	n, err := rand.Int(rand.Reader, big.NewInt(max-min))
	if err != nil {
		return "", err
	}
	v := min + n.Int64()
	return strings.TrimLeft(fmt.Sprintf("%x", v), "0"), nil
}

// randomPoolWithChecksum approximates Vuze/Azureus-style "POOL" peer ids: a
// run of random alphanumeric characters followed by one checksum character
// derived from them. Trackers record peer ids but essentially never validate
// this checksum, so an approximation is sufficient here.
func randomPoolWithChecksum(length int) (string, error) {
	const pool = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
	b := make([]byte, length)
	sum := 0
	for i := 0; i < length-1; i++ {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(pool))))
		if err != nil {
			return "", err
		}
		b[i] = pool[n.Int64()]
		sum += int(b[i])
	}
	b[length-1] = pool[sum%len(pool)]
	return string(b), nil
}

// urlEncode percent-encodes s one byte at a time, leaving bytes matched by
// the profile's encodingExclusionPattern untouched. It deliberately works on
// raw bytes rather than runes: an info_hash or a byte-pool peer id is
// arbitrary binary, not necessarily valid UTF-8, and ranging over such a
// Go string as runes silently mangles any byte that isn't valid UTF-8 into
// U+FFFD before it ever reaches the wire.
func (p *Profile) urlEncode(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		if p.exclusionRe != nil && p.exclusionRe.Match([]byte{c}) {
			b.WriteByte(c)
			continue
		}
		hex := fmt.Sprintf("%%%02X", c)
		if strings.EqualFold(p.URLEncoder.EncodedHexCase, "lower") {
			hex = strings.ToLower(hex)
		}
		b.WriteString(hex)
	}
	return b.String()
}

// urlEncodeBytes percent-encodes raw bytes (used for the 20-byte info_hash),
// following the same exclusion/case rules as urlEncode.
func (p *Profile) urlEncodeBytes(b []byte) string {
	return p.urlEncode(string(b))
}

// QueryParams holds the values substituted into a profile's query template
// for one announce request.
type QueryParams struct {
	InfoHash   [20]byte
	Port       int
	Uploaded   int64
	Downloaded int64
	Left       int64
	Event      string // "started", "stopped", "completed", or "" for a regular announce
	IP         string
	IPv6       string
}

var placeholderRe = regexp.MustCompile(`\{[a-z0-9]+\}`)

// BuildQuery renders the profile's query template into a URL query string
// (without a leading '?'), substituting {placeholders} and dropping any
// param whose placeholder had no value (e.g. {ip}/{event} on a normal
// announce), matching Joal's behaviour so unused params aren't sent as
// empty strings.
func (s *Session) BuildQuery(q QueryParams) (string, error) {
	p := s.profile
	peerID := s.peerID
	if p.PeerIDGenerator.ShouldURLEncode {
		peerID = p.urlEncode(peerID)
	}

	values := map[string]string{
		"infohash":   p.urlEncodeBytes(q.InfoHash[:]),
		"peerid":     peerID,
		"port":       fmt.Sprintf("%d", q.Port),
		"uploaded":   fmt.Sprintf("%d", q.Uploaded),
		"downloaded": fmt.Sprintf("%d", q.Downloaded),
		"left":       fmt.Sprintf("%d", q.Left),
		"key":        s.key,
		"event":      q.Event,
		"numwant":    fmt.Sprintf("%d", q.numwant(p)),
		"ip":         q.IP,
		"ipv6":       q.IPv6,
	}

	// Render param=value pairs individually so an empty-valued placeholder
	// (event/ip/ipv6 on a routine announce) drops the whole "&name=" pair
	// instead of leaving a dangling empty param.
	parts := strings.Split(p.Query, "&")
	var kept []string
	for _, part := range parts {
		rendered := placeholderRe.ReplaceAllStringFunc(part, func(ph string) string {
			key := ph[1 : len(ph)-1]
			return values[key]
		})
		if strings.Contains(rendered, "unresolved") {
			return "", fmt.Errorf("profile: unresolved placeholder in %q", part)
		}
		eq := strings.IndexByte(rendered, '=')
		if eq >= 0 && rendered[eq+1:] == "" {
			name := rendered[:eq]
			if name == "event" || name == "ip" || name == "ipv6" {
				continue
			}
		}
		kept = append(kept, rendered)
	}
	return strings.Join(kept, "&"), nil
}

func (q QueryParams) numwant(p *Profile) int {
	if q.Event == "stopped" {
		return p.NumwantOnStop
	}
	return p.Numwant
}

// BuildHeaders renders the profile's request headers, resolving
// {java}/{os}/{locale} placeholders from the running process.
func (p *Profile) BuildHeaders() []Header {
	replacer := strings.NewReplacer(
		"{java}", runtime.Version(),
		"{os}", fmt.Sprintf("%s %s", runtime.GOOS, runtime.GOARCH),
		"{locale}", "en_US",
	)
	out := make([]Header, len(p.RequestHeaders))
	for i, h := range p.RequestHeaders {
		out[i] = Header{Name: h.Name, Value: replacer.Replace(h.Value)}
	}
	return out
}

// LoadDir loads every *.client profile in dir, keyed by filename without
// extension.
func LoadDir(dir string) (map[string]*Profile, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	profiles := make(map[string]*Profile)
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".client") {
			continue
		}
		p, err := Load(dir + "/" + e.Name())
		if err != nil {
			return nil, err
		}
		profiles[p.Name] = p
	}
	return profiles, nil
}

// Escape is exported for callers (e.g. the RSS/watcher subsystems) that need
// standard URL escaping unrelated to a specific client profile.
func Escape(s string) string { return url.QueryEscape(s) }
